version: '3.7'

services:
    # React
    web:
        build: .
        ports:
          - "80:8000"
        restart: always
        environment:
          NODE_ENV: production
          PORT: 8000
    # Postgres
    postgres:
        environment:
          POSTGRES_USER: raul
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: face-docker
          POSTGRES_HOST: postgres
        build: ./backend/postgres
        ports:
          - "5432:5432"
    # Redis
    redis: 
        image: redis
        ports:
          - "6379:6379"