version: '3.7'

services:
    # React
    frontend:
        build: ./frontend
        volumes: 
          - ./:/usr/src/frontend/
          - .:/frontend/app
        ports:
          - "3001:3000"
    # Backend API
    face-recognition-api:
        container_name: backend
        build: ./backend
        volumes: 
          - ./:/usr/src/backend/
          - .:/backend/app
        command: npm start
        environment:
          POSTGRES_URI: postgres://raul:secret@postgres:5432/face-docker
          REDIS_URI: redis://redis:6379
        links:
          - postgres
          - redis
        ports:
          - "3000:3000"
    # Postgres
    postgres:
        environment:
          POSTGRES_USER: raul
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: face-docker
          POSTGRES_HOST: postgres
        build: ./backend/postgres
        ports:
          - "5432:5432"
    # Redis
    redis: 
        image: redis
        ports:
          - "6379:6379"