version: '3.7'

services:
    # React
    web:
        build: .
        ports:
          - "80:8000"
        restart: always
        env_file:
          ./backend/env
        links:
          - postgres
          - redis
    # Postgres
    postgres:
        restart: always
        env_file:
          - ./backend/env
        build: ./backend/postgres
        ports:
          - "5432:5432"
    # Redis
    redis: 
        restart: always
        env_file:
          ./backend/env
        command: redis-server --requirepass ${REDIS_PASSWORD}
        image: redis
        ports:
          - "6379:6379"