version: '3.7'

services:
    # React
    web:
        build: .
        ports:
          - "80:8000"
        restart: always
        environment:
          NODE_ENV: production
          PORT: 8000
          POSTGRES_URI: postgres://raul:secret@postgres:5432/face-docker
          REDIS_URI: redis://redis:6379
        links:
          - postgres
          - redis
    # Postgres
    postgres:
        restart: always
        environment:
          POSTGRES_USER: raul
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: face-docker
          POSTGRES_HOST: postgres
        build: ./backend/postgres
        ports:
          - "5432:5432"
    # Redis
    redis: 
        restart: always
        image: redis
        ports:
          - "6379:6379"