version: '3.7'

services:
    # Backend API
    face-recognition-api:
        container_name: backend
        build: ./
        volumes: 
          - ./:/usr/src/face-recognition-api
          - .:/app
        command: npm start
        working_dir: /usr/src/face-recognition-api
        environment:
          POSTGRES_URI: postgres://raul:secret@postgres:5432/face-docker
          REDIS_URI: redis://redis:6379
        links:
          - postgres
          - redis
          - nginx
        ports:
          - "3000:3000"
    # Postgres
    postgres:
        container_name: postgres
        environment:
          POSTGRES_USER: raul
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: face-docker
          POSTGRES_HOST: postgres
        build: ./postgres
        ports:
          - "5432:5432"
    # Redis
    redis: 
        container_name: redis
        image: redis
        ports:
          - "6379:6379"
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
          - "80:80"
          - "443:443"